/* Generated by Cython 0.25.1 */

#ifndef __PYX_HAVE__deep_trees__tmc__sample
#define __PYX_HAVE__deep_trees__tmc__sample


#ifndef __PYX_HAVE_API__deep_trees__tmc__sample

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *slice_sample(PyObject *, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__deep_trees__tmc__sample */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initsample(void);
#else
PyMODINIT_FUNC PyInit_sample(void);
#endif

#endif /* !__PYX_HAVE__deep_trees__tmc__sample */
