/* Generated by Cython 0.25.1 */

#ifndef __PYX_HAVE__deep_trees__tmc__util
#define __PYX_HAVE__deep_trees__tmc__util


#ifndef __PYX_HAVE_API__deep_trees__tmc__util

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *log_factorial(float, int __pyx_skip_dispatch);
__PYX_EXTERN_C DL_IMPORT(PyObject) *log_n_choose_k(PyObject *, PyObject *);
__PYX_EXTERN_C DL_IMPORT(PyObject) *tree_factor(int, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__deep_trees__tmc__util */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initutil(void);
#else
PyMODINIT_FUNC PyInit_util(void);
#endif

#endif /* !__PYX_HAVE__deep_trees__tmc__util */
